function ConvertTo-TicketBody {
    param (
        [Parameter(Mandatory)]
        [PSObject]$HealthData
    )

    $sb = [System.Text.StringBuilder]::new()

    [void]$sb.AppendLine("<h2>System Health Alert: $($HealthData.ComputerName)</h2>")
    [void]$sb.AppendLine("<p>")
    [void]$sb.AppendLine("  <strong>Overall Status:</strong> $($HealthData.OverallStatus)<br/>")
    [void]$sb.AppendLine("  <strong>Scan Time:</strong> $($HealthData.Timestamp.ToString('yyyy-MM-dd HH:mm:ss'))<br/>")
    [void]$sb.AppendLine("  <strong>Active Alerts:</strong> $($HealthData.AlertCount)")
    [void]$sb.AppendLine("</p>")

    if ($HealthData.Alerts) {
        [void]$sb.AppendLine("<h3>Active Alerts</h3>")
        [void]$sb.AppendLine("<table border='1' cellpadding='6' style='border-collapse:collapse'>")
        [void]$sb.AppendLine("  <tr><th>Metric</th><th>Value</th><th>Threshold</th><th>Status</th><th>Detail</th></tr>")

        foreach ($alert in $HealthData.Alerts) {
            $bg = if ($alert.Status -eq 'Critical') { '#ffcccc' } else { '#fff3cd' }
            [void]$sb.AppendLine(
                "  <tr style='background:$bg'>" +
                "<td>$($alert.Metric)</td>" +
                "<td><strong>$($alert.Value) $($alert.Unit)</strong></td>" +
                "<td>$($alert.Threshold)</td>" +
                "<td><strong>$($alert.Status)</strong></td>" +
                "<td>$($alert.Detail)</td></tr>"
            )
        }
        [void]$sb.AppendLine("</table>")
    }

    [void]$sb.AppendLine("<h3>Full Health Report</h3>")
    [void]$sb.AppendLine("<table border='1' cellpadding='6' style='border-collapse:collapse'>")
    [void]$sb.AppendLine("  <tr><th>Metric</th><th>Value</th><th>Threshold</th><th>Status</th><th>Detail</th></tr>")

    foreach ($m in $HealthData.AllMetrics) {
        $bg = switch ($m.Status) {
            'Critical' { '#ffcccc' }
            'Warning'  { '#fff3cd' }
            default    { '#d4edda' }
        }
        [void]$sb.AppendLine(
            "  <tr style='background:$bg'>" +
            "<td>$($m.Metric)</td>" +
            "<td>$($m.Value) $($m.Unit)</td>" +
            "<td>$($m.Threshold)</td>" +
            "<td>$($m.Status)</td>" +
            "<td>$($m.Detail)</td></tr>"
        )
    }

    [void]$sb.AppendLine("</table>")
    [void]$sb.AppendLine("<hr/><p><em>Generated by PSHealthWatch, automated Windows health monitoring</em></p>")

    $sb.ToString()
}
