function ConvertTo-TicketBody {
    param (
        [Parameter(Mandatory)]
        [PSObject]$HealthData
    )

    $content = @()

    $content += @{
        type    = 'heading'
        attrs   = @{ level = 2 }
        content = @(@{ type = 'text'; text = "System Health Alert: $($HealthData.ComputerName)" })
    }

    $content += @{
        type    = 'paragraph'
        content = @(
            @{ type = 'text'; text = 'Overall Status: '; marks = @(@{ type = 'strong' }) }
            @{ type = 'text'; text = $HealthData.OverallStatus }
            @{ type = 'hardBreak' }
            @{ type = 'text'; text = 'Scan Time: '; marks = @(@{ type = 'strong' }) }
            @{ type = 'text'; text = $HealthData.Timestamp.ToString('yyyy-MM-dd HH:mm:ss') }
            @{ type = 'hardBreak' }
            @{ type = 'text'; text = 'Active Alerts: '; marks = @(@{ type = 'strong' }) }
            @{ type = 'text'; text = $HealthData.AlertCount.ToString() }
        )
    }

    if ($HealthData.Alerts) {
        $content += @{
            type    = 'heading'
            attrs   = @{ level = 3 }
            content = @(@{ type = 'text'; text = 'Active Alerts' })
        }
        $content += New-AdfTable -Rows $HealthData.Alerts
    }

    $content += @{
        type    = 'heading'
        attrs   = @{ level = 3 }
        content = @(@{ type = 'text'; text = 'Full Health Report' })
    }
    $content += New-AdfTable -Rows $HealthData.AllMetrics

    $content += @{
        type    = 'paragraph'
        content = @(@{
            type  = 'text'
            text  = 'Generated by PSHealthWatch, automated Windows health monitoring'
            marks = @(@{ type = 'em' })
        })
    }

    return @{
        type    = 'doc'
        version = 1
        content = $content
    }
}
